language: node_js
node_js: 8
cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: true
    addons:
      apt:
        packages:
          - rpm
          - g++-multilib
          - libxss-dev:i386
          - snapd
  - os: osx
    osx_image: xcode8.3

branches:
  only:
    - master
    - develop
    - /^hotfix\/.*$/
    - /^release\/.*$/

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi

install:
  - yarn
  - yarn list

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export CSC_IDENTITY_AUTO_DISCOVERY=false; fi
  # e2e tests should be performed only on Linux
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
      yarn e2e
    fi
  - yarn release
